version: "3.2"
services:
  sensor:
    build: './sensors/'
    networks:
      - vp1

  sink:
    build: './sinks/'
    networks:
      - vp1
      
networks:
  vp1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16